version: '3.8'

services:
  kind:
    build: ./kind-service
    container_name: kind
    networks:
      - kind
    volumes:
      - kind-data:/var/lib/docker
      - ./kube_dir:/root/.kube  # Share the kubeconfig file
      - ./setup_kind.sh:/setup_kind.sh
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: ["sh", "/setup_kind.sh"]      
    # entrypoint: ["sh"]  # Changed to start with a shell       
    # stdin_open: true  # Keep stdin open
    # tty: true         # Allocate a pseudo-TTY  

  python-client:
    build: ./python-client
    container_name: python-client
    environment:
      - KUBECONFIG=/root/.kube/config
    networks:
      - kind
    volumes:
      - ./kube_dir:/root/.kube  # Share the kubeconfig file
    depends_on:
      - kind
    entrypoint: ["python", "/usr/src/app/client.py"]
    # entrypoint: ["sh"]  # Changed to start with a shell        
    # stdin_open: true  # Keep stdin open
    # tty: true         # Allocate a pseudo-TTY  


volumes:
  kind-data:

networks:
  # MUST create the network before running the containers
  # The network `kind-control-plane` container joins and it cannot be reconfigured
  kind: 
    external: true